# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  # centrals
  - board: nrf52840dk_nrf52840
    shield: matze_dongle
  - board: nice_nano_v2
    shield: matze_central_left
  # peripherals
  - board: nice_nano_v2
    shield: matze_left
  - board: nice_nano_v2
    shield: matze_right
  # To reset the boards
  - board: nice_nano_v2
    shield: settings_reset
  - board: nrf52840dk_nrf52840
    shield: settings_reset
